հաversion: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: microservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d microservice_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db-orders:
    image: postgres:15
    container_name: postgres_orders_db
    restart: always
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - ecommerce-network
    volumes:
      - postgres-orders-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db-notifications:
    image: postgres:15
    container_name: postgres_notifications_db
    restart: always
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - ecommerce-network
    volumes:
      - postgres-notifications-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notifications_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db-auth:
    image: postgres:15
    container_name: postgres_auth_db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - ecommerce-network
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db-analytics:
    image: postgres:15
    container_name: postgres_analytics_db
    restart: always
    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    networks:
      - ecommerce-network
    volumes:
      - postgres-analytics-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d analytics_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db-users:
    image: postgres:15
    container_name: postgres_users_db
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    networks:
      - ecommerce-network
    volumes:
      - postgres-users-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  product-service:
    image: ${DOCKER_HUB_USER}/product-service:latest
    build:
      context: ./product/ProductService
      dockerfile: ../Dockerfile
    container_name: product-service
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/microservice_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx256m"
    restart: always
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  order-service:
    image: ${DOCKER_HUB_USER}/order-service:latest
    build:
      context: ./order/Order-Service
      dockerfile: ../Dockerfile
    container_name: order-service
    depends_on:
      db-orders:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8083:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-orders:5432/orders_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PRODUCT_SERVICE_URL: http://product-service:8080
      USER_SERVICE_URL: http://user-service:8080
      NOTIFICATION_SERVICE_URL: http://notification-service:8080
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx256m"
    restart: always
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  notification-service:
    image: ${DOCKER_HUB_USER}/notification-service:latest
    build:
      context: ./notification/Notifictaion-Service
      dockerfile: ../Dockerfile
    container_name: notification-service
    depends_on:
      db-notifications:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8086:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-notifications:5432/notifications_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ORDER_SERVICE_URL: http://order-service:8080
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx200m"
    restart: always
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  auth-service:
    image: ${DOCKER_HUB_USER}/auth-service:latest
    build:
      context: ./auth/auth-service
      dockerfile: ../../gateway/Dockerfile
    container_name: auth-service
    depends_on:
      db-auth:
        condition: service_healthy
      user-service:
        condition: service_started
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-auth:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      USER_SERVICE_URL: http://user-service:8080
      FRONTEND_URL: http://167.233.226.5
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx200m"
    restart: always
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  user-service:
    image: ${DOCKER_HUB_USER}/user-service:latest
    build:
      context: ./user/user-service/user-service
      dockerfile: ../../Dockerfile
    container_name: user-service
    depends_on:
      db-users:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8084:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-users:5432/users_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx200m"
    restart: always
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - minio-data:/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  image-service:
    image: ${DOCKER_HUB_USER}/image-service:latest
    build:
      context: ./image/image-service/image-service
      dockerfile: ../../Dockerfile
    container_name: image-service
    depends_on:
      minio:
        condition: service_healthy
    ports:
      - "8085:8080"
    environment:
      SERVER_PORT: 8080
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ROOTUSER
      MINIO_SECRET_KEY: CHANGEME123
      MINIO_BUCKET_NAME: order-images
      MINIO_REGION: us-east-1
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx200m"
    restart: always
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  analytics-service:
    image: ${DOCKER_HUB_USER}/analytics-service:latest
    build:
      context: ./analytics/analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    depends_on:
      db-analytics:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8087:8080"
    environment:
      SERVER_PORT: 8080
      DB_HOST: db-analytics
      DB_USER: postgres
      DB_PASS: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      ORDER_SERVICE_URL: http://order-service:8080
      PRODUCT_SERVICE_URL: http://product-service:8080
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx200m"
    restart: always
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  gateway-service:
    image: ${DOCKER_HUB_USER}/gateway-service:latest
    build:
      context: ./gateway/gateway-service
      dockerfile: ../Dockerfile
    container_name: gateway-service
    depends_on:
      - auth-service
      - product-service
      - order-service
      - notification-service
      - user-service
      - image-service
      - analytics-service
      - payment-service
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      PRODUCT_SERVICE_URL: http://product-service:8080
      ORDER_SERVICE_URL: http://order-service:8080
      AUTH_SERVICE_URL: http://auth-service:8080
      NOTIFICATION_SERVICE_URL: http://notification-service:8080
      USER_SERVICE_URL: http://user-service:8080
      IMAGE_SERVICE_URL: http://image-service:8080
      ANALYTICS_SERVICE_URL: http://analytics-service:8080
      PAYMENT_SERVICE_URL: http://payment-service:8080
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx256m"
    restart: always
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  payment-db:
    image: postgres:15
    container_name: postgres_payment_db
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    networks:
      - ecommerce-network
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  payment-service:
    image: ${DOCKER_HUB_USER}/payment-service:latest
    build:
      context: ./payment/payment-service/Payment-Service
      dockerfile: Dockerfile
    container_name: payment-service
    depends_on:
      payment-db:
        condition: service_healthy
      user-service:
        condition: service_started
    ports:
      - "8088:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      USER_SERVICE_URL: http://user-service:8080
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx200m"
    restart: always
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ${DOCKER_HUB_USER}/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - gateway-service
    restart: always
    networks:
      - ecommerce-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres-data:
  postgres-orders-data:
  postgres-notifications-data:
  postgres-auth-data:
  postgres-users-data:
  postgres-analytics-data:
  postgres-payment-data:
  minio-data:
