<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>mikroservis-root</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Mikroservis Root</name>

    <modules>
        <module>gateway/gateway-service</module>
        <module>auth2/auth-service</module>
        <module>product/ProductService</module>
        <module>order/Order-Service</module>
        <module>user/user-service/user-service</module>
        <module>notification/Notifictaion-Service</module>
        <module>image/image-service/image-service</module>
        <module>analytics/analytics-service</module>
        <module>payment/payment-service/Payment-Service</module>
    </modules>

</project>
