spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
            required: true

server:
  port: 8091

jwt:
  secret: ${JWT_SECRET:A9gX7mP2qK5zW1vB8nR4tY0eU3iO6pL9sJ2dH5fG8hK1lM4nJ3bV6cC9vX0zZ1qA}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:4200}